// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginRequest struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type LoginResponse struct {
	Token string `json:"Token"`
	User  *User  `json:"User"`
}

type Mutation struct {
}

type Query struct {
}

type Role struct {
	ID   string `json:"Id"`
	Name string `json:"Name"`
}

type User struct {
	ID        string  `json:"Id"`
	Role      *Role   `json:"Role,omitempty"`
	Username  *string `json:"Username,omitempty"`
	Firstname *string `json:"Firstname,omitempty"`
	Lastname  *string `json:"Lastname,omitempty"`
	Email     *string `json:"Email,omitempty"`
}
